# FrontEnd
trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: azure-static-web-apps-black-grass-04c403c0f-variable-group

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.16.0'
    displayName: 'Instalar Node.js'

  - checkout: self
    submodules: true

  - script: |
      cd Tesis-SG-Front
      npm install
      npx vite --mode production build
    displayName: 'Instalar dependencias y compilar el proyecto con Vite'

  - task: AzureStaticWebApp@0
    displayName: 'Desplegar en Azure Static Web App'
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_GRASS_04C403C0F)
      app_location: "client"
      output_location: "dist"



