# FrontEnd
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Azure-Static-Web-Apps-NiuBroker-variable-group

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Instalar Node.js'

  - checkout: self
    submodules: true

  - script: |
      cd Tesis-SG-Front
      npm install
      npm run build
    displayName: 'Instalar dependencias y compilar el proyecto con Vite'

  - task: AzureStaticWebApp@0
    displayName: 'Desplegar en Azure Static Web App'
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_GR_04C403C0F)
      app_location: "client"
      output_location: "dist"



