name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: azure-static-web-apps-black-grass-04c403c0f-variable-group

jobs:
  - job: build_and_deploy
    displayName: Build and Deploy to Azure Static Web Apps
    steps:
      - checkout: self

      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: |
          cd Tesis-SG-Front
          npm install
          chmod +x ./node_modules/.bin/vite
          export PATH=$PATH:./node_modules/.bin
          npm run build
        displayName: 'Install dependencies and build project with Vite'

      - script: |
          echo '{
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/images/*.{png,jpg,gif,ico}", "/css/*", "/js/*"]
            }
          }' > Tesis-SG-Front/staticwebapp.config.json
        displayName: 'Create staticwebapp.config.json for SPA routing'

      - task: AzureStaticWebApp@0
        inputs:
          azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_GRASS_04C403C0F)
          app_location: 'Tesis-SG-Front'
          app_build_command: 'npm run build'
          output_location: 'dist'
          deployment_environment: 'development'
        displayName: 'Deploy to Azure Static Web Apps'
